email = "popu-servers+jenkins@populate.tools "
pipeline {
    agent any
    environment {
        PATH = "$HOME/.rbenv/shims:$PATH"
        GOBIERTO_ETL_UTILS = "/var/www/gobierto-etl-utils/current"
        EUSKADI_ETL = "/var/www/gobierto-etl-euskadi/current"
        STORAGE_DIR = "${EUSKADI_ETL}/tmp"
        // Variables that must be defined via Jenkins UI:
        // RAILS_ENV = "production"
    }
    stages {
        stage('Extract > Clear storage dir') {
            steps {
                sh "rm -rf ${STORAGE_DIR}/*"
            }
        }
        stage('Extract > Download data') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/api-download/run.rb --source-url 'https://www.eustat.eus/bankupx/Resources/PX/Databases/DB/PX_153011_cepsp_pspmun04.px' --output-file ${STORAGE_DIR}/PX_153011_cepsp_pspmun04.px
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/api-download/run.rb --source-url 'https://www.eustat.eus/bankupx/Resources/PX/Databases/DB/PX_153011_cepsp_pspmun05.px' --output-file ${STORAGE_DIR}/PX_153011_cepsp_pspmun05.px
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/api-download/run.rb --source-url 'https://www.eustat.eus/bankupx/Resources/PX/Databases/DB/PX_153011_cepsp_psppre01.px' --output-file ${STORAGE_DIR}/PX_153011_cepsp_psppre01.px
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/api-download/run.rb --source-url 'https://www.eustat.eus/bankupx/Resources/PX/Databases/DB/PX_153011_cepsp_psppre02.px' --output-file ${STORAGE_DIR}/PX_153011_cepsp_psppre02.px
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/api-download/run.rb --source-url 'https://www.eustat.eus/bankupx/Resources/PX/Databases/DB/PX_153011_cepsp_pspmun06.px' --output-file ${STORAGE_DIR}/PX_153011_cepsp_pspmun06.px
            }
        }
        stage('Transform > Convert px files to UTF8') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/convert-to-utf8/run.rb ${STORAGE_DIR}/PX_153011_cepsp_pspmun04.px ${STORAGE_DIR}/PX_153011_cepsp_pspmun04_utf8.px ISO-8859-1"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/convert-to-utf8/run.rb ${STORAGE_DIR}/PX_153011_cepsp_pspmun05.px ${STORAGE_DIR}/PX_153011_cepsp_pspmun05_utf8.px ISO-8859-1"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/convert-to-utf8/run.rb ${STORAGE_DIR}/PX_153011_cepsp_psppre01.px ${STORAGE_DIR}/PX_153011_cepsp_psppre01_utf8.px ISO-8859-1"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/convert-to-utf8/run.rb ${STORAGE_DIR}/PX_153011_cepsp_psppre02.px ${STORAGE_DIR}/PX_153011_cepsp_psppre02_utf8.px ISO-8859-1"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/convert-to-utf8/run.rb ${STORAGE_DIR}/PX_153011_cepsp_pspmun06.px ${STORAGE_DIR}/PX_153011_cepsp_pspmun06_utf8.px ISO-8859-1"
            }
        }
        stage('Transform > Transform PX data do JSON') {
            steps {
                sh "cd ${EUSKADI_ETL}; ruby operations/gobierto-budgets/transform-px-data/run.rb ${STORAGE_DIR}/PX_153011_cepsp_pspmun04_utf8.px ${STORAGE_DIR}/PX_153011_cepsp_pspmun04.json"
                sh "cd ${EUSKADI_ETL}; ruby operations/gobierto-budgets/transform-px-data/run.rb ${STORAGE_DIR}/PX_153011_cepsp_pspmun05_utf8.px ${STORAGE_DIR}/PX_153011_cepsp_pspmun05.json"
                sh "cd ${EUSKADI_ETL}; ruby operations/gobierto-budgets/transform-px-data/run.rb ${STORAGE_DIR}/PX_153011_cepsp_psppre01_utf8.px ${STORAGE_DIR}/PX_153011_cepsp_psppre01.json"
                sh "cd ${EUSKADI_ETL}; ruby operations/gobierto-budgets/transform-px-data/run.rb ${STORAGE_DIR}/PX_153011_cepsp_psppre02_utf8.px ${STORAGE_DIR}/PX_153011_cepsp_psppre02.json"
                sh "cd ${EUSKADI_ETL}; ruby operations/gobierto-budgets/transform-px-data/run.rb ${STORAGE_DIR}/PX_153011_cepsp_pspmun06_utf8.px ${STORAGE_DIR}/PX_153011_cepsp_pspmun06.json"
            }
        }
        stage('Load > Import data') {
            steps {
                sh "cd ${EUSKADI_ETL}; ruby operations/gobierto-budgets/load-json-data/run.rb ${STORAGE_DIR}/PX_153011_cepsp_pspmun04.json"
                sh "cd ${EUSKADI_ETL}; ruby operations/gobierto-budgets/load-json-data/run.rb ${STORAGE_DIR}/PX_153011_cepsp_pspmun05.json"
                sh "cd ${EUSKADI_ETL}; ruby operations/gobierto-budgets/load-json-data/run.rb ${STORAGE_DIR}/PX_153011_cepsp_psppre01.json"
                sh "cd ${EUSKADI_ETL}; ruby operations/gobierto-budgets/load-json-data/run.rb ${STORAGE_DIR}/PX_153011_cepsp_psppre02.json"
                sh "cd ${EUSKADI_ETL}; ruby operations/gobierto-budgets/load-json-data/run.rb ${STORAGE_DIR}/PX_153011_cepsp_pspmun06.json"
            }
        }
        stage('Load > Re-calculate bubbles') {
            steps {
                sh "cd ${EUSKADI_ETL}; ruby operations/gobierto-budgets/generate-location-ids/run.rb ${STORAGE_DIR}/location_ids.txt"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/bubbles/run.rb ${STORAGE_DIR}/location_ids.txt"
            }
        }
    }
    post {
        failure {
            echo "This will run only if failed"
            mail body: "Project: ${env.JOB_NAME} - Build Number: ${env.BUILD_NUMBER} - URL de build: ${env.BUILD_URL}",
                charset: "UTF-8",
                subject: "ERROR CI: Project name -> ${env.JOB_NAME}",
                to: email
        }
    }
}
